package de.fhg.iais.roberta.visitor;

public enum CalliopeMethods {
    IS_GESTURE_SHAKE,
    ULTRASONIC_GET_DISTANCE,
    LED_BAR_SET_LED,
    SET_MATRIX_BRIGHTNESS,
    SET_BOTH_MOTORS,
    SET_MOTOR,
    SERVO_GET_ANGLE,
    RECEIVE_MESSAGE,
    GET_ROTATION,
    SETUP_WIFI,
    SETUP_IBM,
    SEND_AND_WAIT,
    SIMULATE_QBIT_MEASURE,
    PARSE_LIST_RESPONSE,
    GET_CLEAN_RESPONSE,
    START_REAL_QBIT_JOB,
    IBM_GET_JOB_RESULT,
    IBM_GET_JOB_STATUS,
}